name: release

on:
  release:
    types: [published]
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Compile Typescript
        run: yarn tsc
      - name: Publish
        run: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
